---
application:
  name: "vvvvv"
  project: "aef"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "leaf"
  version: "11"
routers:
- name: "main-vvvvv"
  routes:
  - application_name: "vvvvv"
    paths:
    - "/*"
